"""Auto migration

Revision ID: 401cf2de4874
Revises: 
Create Date: 2025-06-18 13:05:55.301767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '401cf2de4874'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_mfo_mapping', sa.Column('driver_salary', sa.DOUBLE_PRECISION(), nullable=True))
    op.add_column('vehicle_costing', sa.Column('is_enable', sa.Boolean(), nullable=True))
    op.add_column('vehicle_costing', sa.Column('disabled_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('vehicle_costing', 'driver_salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_costing', sa.Column('driver_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('vehicle_costing', 'disabled_at')
    op.drop_column('vehicle_costing', 'is_enable')
    op.drop_column('driver_mfo_mapping', 'driver_salary')
    # ### end Alembic commands ###
